// ESLint flat config. `eslint-config-expo` brings the React Native, import and
// a11y rules that match this SDK; `eslint-config-prettier` switches off the
// stylistic rules Prettier already owns.
const expoConfig = require('eslint-config-expo/flat');
const prettierConfig = require('eslint-config-prettier');

module.exports = [
  ...expoConfig,
  prettierConfig,
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'android/**',
      'ios/**',
      'dist/**',
      '.claude/**',
      // Generated by drizzle-kit; regenerated with `npm run db:generate`.
      'drizzle/**',
      'expo-env.d.ts',
    ],
  },
  {
    // Jest setup runs in CommonJS and has to `require` the Reanimated mock
    // lazily inside the factory — `jest.mock` hoists above ES imports.
    files: ['jest.setup.ts'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // `src/db/testDatabase.ts` pulls in better-sqlite3, a Node native module
    // that cannot run on a device. Importing it from app code would break the
    // bundle at runtime rather than at build time, so it is blocked here.
    files: ['app/**/*.{ts,tsx}', 'src/**/*.{ts,tsx}'],
    ignores: ['**/__tests__/**', 'src/db/testDatabase.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@/db/testDatabase',
              message:
                'Test-only: better-sqlite3 cannot run on a device. Use `@/db/client` instead.',
            },
          ],
        },
      ],
    },
  },
  {
    rules: {
      'import/order': [
        'warn',
        {
          groups: [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']],
          pathGroups: [{ pattern: '@/**', group: 'internal' }],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Build-time Node scripts, not app code: stdout is their whole point.
    files: ['scripts/**/*.mjs'],
    rules: { 'no-console': 'off' },
  },
];
